name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Create input.txt
      run: |
        echo "1" > input.txt
        echo "1" >> input.txt
        echo "2" >> input.txt
        echo "4" >> input.txt
        echo "2" >> input.txt
        echo "1" >> input.txt
        echo "Paracetamol" >> input.txt
        echo "15000" >> input.txt
        echo "n" >> input.txt
        echo "11" >> input.txt
        echo "3" >> input.txt
        echo "1" >> input.txt
        echo "Paracetamol" >> input.txt
        echo "1" >> input.txt
        echo "5" >> input.txt
        echo "4" >> input.txt

    - name: Compile C++ code
      run: g++ -o main Apotek.cpp

    - name: Run the program with input.txt
      run: ./main < input.txt
